name: Scheduled Merge Remote Action
on: 
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'
    # scheduled for every Hour

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream - master
        uses: Cubik65536/merge-upstream@v1.1.3
        with:
          upstream: CubikLab/fa-lang-doc-demo # set the upstream repo
          upstream-branch: main   # set the upstream branch to merge from
          branch: main            # set the branch to merge to
